### ISSUE TITLE
Your code is completely broken

### ISSUE THREAD

**Issue by w0298i** [drhacko/lividus#1]
I'll take a look later. The *big* mistake is checking `o.x == null || undefined`. `undefined` is treated as a seperate expression. Why not just check `o.x == null`? The double eq also returns true if it is undefined.

**Comment by w0298i** [comment]
btw hi devr

**Comment by drhacko** [comment]
ik. im not a pro

**Comment by w0298i** [comment]
ur gay

**Comment by w0298i** [comment]
rekt
